#spring:
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#  cache: 
#    type: redis    
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password: radar
#    database: 0
#    timeout: 5000 
#    lettuce:
#      pool:
#        max-active: 16
#        max-wait: 2000
#        max-idle: 8
#        min-idle: 4
#  klock:
#    address: 127.0.0.1:6379
#    password: radar
#    database: 3
#    waitTime: 10
#    leaseTime: 10
#    
#  servlet:
#    multipart:
#      max-file-size: 100MB
#      max-request-size: 100MB
#  cloud:
#    sentinel:
#      eager: true
#      filter:
#        enabled: false
#      transport:
#        dashboard: feng-sentinel:5020
#
#management:
#  metrics.export.prometheus.enabled: true
#  endpoints:
#    enabled-by-default: false
#    web:
#      exposure:
#        include: '*'          
#  endpoint:
#    metrics:
#      enabled: true
#    prometheus:
#      enabled: true
#    restart:
#      enabled: true
#    health:
#      show-details: ALWAYS
#
#feign:
#  sentinel:
#    enabled: true
#  okhttp:
#    enabled: true
#  httpclient:
#    enabled: false
#  client:
#    config:
#      default:
#        connectTimeout: 20000
#        readTimeout: 20000
#  compression:
#    request:
#      enabled: true
#    response:
#      enabled: true
#
#
#gray:
#  rule:
#    enabled: true
#
#mybatis-plus:
#  tenant-enable: false
#  mapper-locations: classpath:/mapper/*Mapper.xml
#  global-config:
#    capitalMode: true
#    banner: false
#    db-config:
#      id-type: auto
#      select-strategy: NOT_NULL
#      insert-strategy: NOT_NULL
#      update-strategy: NOT_NULL
#  type-handlers-package:  work.metanet.feng.common.data.handler, work.metanet.feng.admin.api.handler
#  configuration:
#    jdbc-type-for-null: 'null'
#    call-setters-on-nulls: true
#
#params:
#  dataTimeType: date
#
#feng:
#  websocket:
#    lifespan: 60
#
#springdoc:
#  api-docs:
#    path: /v3/api-docs
#  swagger-ui:
#    path: /swagger-ui.html
#    tags-sorter: alpha
#    operations-sorter: alpha
#    enabled: true
#  group-configs:
#    - group: 'default'
#      paths-to-match: '/**'
#
#knife4j:
#  enable: true
#  setting:
#    language: zh-CN
#    enable-swagger-models: true
#    enable-document-manage: true
#    enable-version-strategy: false
#
#bi: 
#  token: 123456